# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'MQTTClient'
target 'MQTT iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MQTT iOS

  target 'MQTT iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MQTT iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
